import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<div className="relative min-h-dvh bg-gradient-to-b from-white via-rose-50/50 to-sky-50/40">
					<div className="pointer-events-none absolute inset-0 [mask-image:radial-gradient(65%_45%_at_50%_0%,#000_30%,transparent_100%)]">
						<div className="-translate-x-1/2 absolute top-[-140px] left-1/2 h-[280px] w-[560px] rounded-full bg-gradient-to-r from-rose-200/40 via-pink-200/30 to-sky-200/40 blur-3xl" />
					</div>
					{children}
				</div>
			</body>
		</html>
	);
}
